### PR TITLE
Upgrade to 96.0.4664.x

### PR DESCRIPTION
**Pull request by henrik242**
See
- https://omahaproxy.appspot.com/
- https://chromedriver.storage.googleapis.com/index.html?path=96.0.4664.45/

### CODE REVIEW

**Comment by henrik242** [comment]
@okv New version for you :) (and me!)

**Comment by okv** [comment]
Hey @henrik242, the PR itself looks good but the builds are failing. Could you take a look at it?

**Comment by henrik242** [comment]
@okv Seems like `write-revisions.js` isn't working for some reason. Any ideas what it could be?

**Comment by henrik242** [comment]
Superseded by https://github.com/2do2go/node-chromium/pull/9

**Pull request closed without merging**
