### PR TITLE
Change file name prefix of Windows download from 'win32' to 'win'.

### PR DESCRIPTION
**Pull request by MartinKolarik**
Currently it's broken on Windows.

### CODE REVIEW

**Comment by wrager** [comment]
@okv What about merging this? `require('chromium-binary').path` is invalid on Windows.

**Comment by okv** [comment]
Hi, there.
The patch needs to be reworked - conflict should be resolved (e.g. by merging master into fix branch) and tests should be green)

**Comment by MartinKolarik** [comment]
I actually just took the upstream commit without forking so I can't really rebase it. But it's just two lines, you can either manually copy it or I'll create a new PR with a new commit if you prefer.

**Comment by okv** [comment]
New PR would be great

**Comment by MartinKolarik** [comment]
#5

**Pull request closed without merging**
