### PR TITLE
Update to v74.0.3729.131

### PR DESCRIPTION
**Pull request by henrik242**

### CODE REVIEW

**Comment by henrik242** [comment]
@okv  Hm, I have no idea why operationSystemRevisions.json is removed. Any ideas?

**Comment by okv** [comment]
The problem is exact version of chromium "75.0.3770.8" is not found at https://omahaproxy.appspot.com (service which is used to find chromium archives by version).

Try to use another version. To discover different versions of chromium you can use:

* https://omahaproxy.appspot.com
* https://www.chromium.org/getting-involved/download-chromium
 
P.s. If it suitable for you please use stable versions of chromium (which is recommended for most users).

**Comment by henrik242** [comment]
Ah, thanks.  I was only looking at the latest version @ http://chromedriver.chromium.org/downloads

I've amended the commit with a sane version

**Comment by henrik242** [comment]
Green builds for everything but Node 6. Who uses that nowadays, I wonder? 🤔🙂

**Comment by henrik242** [comment]
All green :)  @okv Would you be able to merge this and push a release to npmjs.com?

**Comment by okv** [comment]
chromium-binary@74.0.3729-131 published to npm.
Thanks for your contribution.

**Pull request merged**
