### PR TITLE
Update to latest stable version of chromium (v76.0.3809.87)

### PR DESCRIPTION
**Pull request by glacambre**
Hi. Thank you for maintaining this repo. I tried to update your package by doing the same thing I saw in https://github.com/2do2go/node-chromium/pull/3, please let me know if there's anything I should change.

### CODE REVIEW

**Comment by okv** [comment]
You're welcome )
PR looks good, going to merge...

**Comment by okv** [comment]
published to npm as chromium-binary@76.0.3809-87
Thanks for your contribution.

**Comment by henrik242** [comment]
@okv @glacambre Any plans on updating again? 😄

**Comment by henrik242** [comment]
Never mind: https://github.com/2do2go/node-chromium/pull/7 😸

**Pull request merged**
